### ISSUE TITLE
Memory leak(s) when modifying `PATH` in various contexts

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#405]
These regression tests leak: https://github.com/ksh93/ksh/blob/5422af4e333e7c37c6beb46e7173c3653e8a0eaa/src/cmd/ksh93/tests/leaks.sh#L355-L368 https://github.com/ksh93/ksh/blob/5422af4e333e7c37c6beb46e7173c3653e8a0eaa/src/cmd/ksh93/tests/leaks.sh#L376-L394

I don't know if these are all different leaks, all the same leak, or neither.

Relevant results on macOS when running `DEBUG=y bin/shtests -p leaks`:
```
	leaks.sh[368]: FAIL: known leak: unset PATH in main shell: leaked approx 6596 KiB after 16384 iterations -- help us fix it at: https://github.com/ksh93/ksh/issues/405
	leaks.sh[379]: FAIL: known leak: set PATH value in subshell: leaked approx 9140 KiB after 16384 iterations -- help us fix it at: https://github.com/ksh93/ksh/issues/405
	leaks.sh[384]: FAIL: known leak: run command with preceding PATH assignment in subshell: leaked approx 748 KiB after 16384 iterations -- help us fix it at: https://github.com/ksh93/ksh/issues/405
	leaks.sh[389]: FAIL: known leak: set PATH attribute in subshell: leaked approx 9596 KiB after 16384 iterations -- help us fix it at: https://github.com/ksh93/ksh/issues/405
	leaks.sh[394]: FAIL: known leak: unset PATH in subshell: leaked approx 15964 KiB after 16384 iterations -- help us fix it at: https://github.com/ksh93/ksh/issues/405
```

**Comment by atheik** [comment]
Edit: The restoring of special variables, as defined by `nv_cover()`, with the `NV_INTEGER` attribute is broken in this patch. The change to `put_seconds()` is also wrong.
-
I understand very little of this codebase so these changes were mostly
guided by stepping through the program with GDB and Valgrind:
```diff
diff --git a/src/cmd/ksh93/sh/init.c b/src/cmd/ksh93/sh/init.c
index f029b6c7..c2c32f78 100644
--- a/src/cmd/ksh93/sh/init.c
+++ b/src/cmd/ksh93/sh/init.c
@@ -634,6 +634,7 @@ static void put_seconds(register Namval_t* np,const char *val,int flags,Namfun_t
 		nv_setsize(np,3);
 		nv_onattr(np,NV_DOUBLE);
 		np->nvalue.dp = new_of(double,0);
+		nv_offattr(np,NV_NOFREE);
 	}
 	nv_putv(np, val, flags, fp);
 	d = *np->nvalue.dp;
diff --git a/src/cmd/ksh93/sh/path.c b/src/cmd/ksh93/sh/path.c
index 9b13f941..189c8787 100644
--- a/src/cmd/ksh93/sh/path.c
+++ b/src/cmd/ksh93/sh/path.c
@@ -392,8 +392,7 @@ static void pathinit(void)
 	}
 	else
 	{
-		pp = defpathinit();
-		sh.pathlist = (void*)path_dup(pp);
+		sh.pathlist = pp = defpathinit();
 	}
 	if(val=sh_scoped((FPATHNOD))->nvalue.cp)
 	{
@@ -1631,7 +1630,7 @@ Pathcomp_t *path_addpath(Pathcomp_t *first, register const char *path,int type)
 	if(old)
 	{
 		if(!first && !path)
-			first = path_dup(defpathinit());
+			first = defpathinit();
 		if(cp=(sh_scoped(FPATHNOD))->nvalue.cp)
 			first = (void*)path_addpath((Pathcomp_t*)first,cp,PATH_FPATH);
 		path_delete(old);
diff --git a/src/cmd/ksh93/sh/subshell.c b/src/cmd/ksh93/sh/subshell.c
index e0bab084..b5965170 100644
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -227,6 +227,7 @@ int nv_subsaved(register Namval_t *np, int flags)
 					else
 						sp->svar = lp->next;
 					free((void*)np);
+					free((void*)((Namval_t*)&lp->dict)->nvfun);
 					free((void*)lp);
 				}
 				return(1);
@@ -361,6 +362,8 @@ static void nv_restore(struct subshell *sp)
 		nv_setsize(mp,nv_size(np));
 		if(!(flags&NV_MINIMAL))
 			mp->nvenv = np->nvenv;
+		if(mp->nvfun && !mp->nvfun->nofree)
+			free((char*)mp->nvfun);
 		mp->nvfun = np->nvfun;
 		if(np->nvfun && nofree)
 			np->nvfun->nofree = nofree;
@@ -371,9 +374,18 @@ static void nv_restore(struct subshell *sp)
 		}
 		mp->nvflag = np->nvflag|(flags&NV_MINIMAL);
 		if(nv_cover(mp))
-			nv_putval(mp,nv_getval(np),NV_RDONLY);
+		{
+			if(nv_isattr(np,NV_INTEGER))
+			{
+				nv_putval(mp,nv_getval(np),(np->nvflag&~NV_INTEGER)|NV_RDONLY);
+				if (!nv_isattr(np,NV_NOFREE))
+					free((void*)np->nvalue.ip);
+			}
+			else
+				nv_putval(mp,nv_getval(np),np->nvflag|NV_RDONLY|NV_NOFREE);
+		}
 		else
-			mp->nvalue = np->nvalue;
+			mp->nvalue.cp = np->nvalue.cp;
 		if(nofree && np->nvfun && !np->nvfun->nofree)
 			free((char*)np->nvfun);
 		np->nvfun = 0;

```

This patch also concerns issue #404.
While bin/shtests did pass, I would be surprised if I didn't break something.

In the patch, the only changes that don't deal with leaks are the first
path_dup removal and the nvalue.cp assignment change which were done just
for consistency. The second path_dup removal does fix a leak and probably
breaks something.

These leaks are not covered by bin/shtests but I fixed the first one with the change
to the put_seconds function:
```
ksh -c '(unset SECONDS)'
ksh -c '(unset SECONDS);(unset SECONDS)' # ...
```

I think this one is more related to issue #94 instead:
https://github.com/ksh93/ksh/blob/333a8ca/src/cmd/ksh93/tests/leaks.sh#L355-L361

**Comment by atheik** [comment]
>I think this one is more related to issue https://github.com/ksh93/ksh/issues/94 instead:
>https://github.com/ksh93/ksh/blob/333a8ca/src/cmd/ksh93/tests/leaks.sh#L355-L361

Nevermind, it is not, but the following does fix the leak in issue #94:
```diff
diff --git a/src/cmd/ksh93/sh/subshell.c b/src/cmd/ksh93/sh/subshell.c
index b5965170..308c2b66 100644
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -353,6 +353,8 @@ static void nv_restore(struct subshell *sp)
 		if(nv_isarray(mp))
 			 nv_putsub(mp,NIL(char*),ARRAY_SCAN);
 		nofree = mp->nvfun?mp->nvfun->nofree:0;
+		if(mp->nvalue.cp!=Empty && np->nvalue.cp==Empty)
+			nv_offattr(mp,NV_NOFREE);
 		_nv_unset(mp,NV_RDONLY|NV_CLONE);
 		if(nv_isarray(np))
 		{

```

**Comment by McDutchie** [comment]
A little progress was made in 11981f5fd6d6d6cb758ddf176b47126162daa618 (dev), a96b84818e5baaf81f0b9db88506fa636ef46a70 (1.0).

**Comment by vmihalko** [comment]
Checking HEAD - still reproducible with the latest dev branch as well as 1.0.10 and 1.0.6. Our (redhat) test assigns PATH in a loop for 50k iterations and RSS keeps growing throughout.

Valgrind shows no definite leaks, only still-reachable allocations.

Is there any progress on a fix, or pointers on where in the PATH handling the memory grows?

**Comment by McDutchie** [comment]
No progress. I only have so much time for ksh and there are still higher-priority bugs. Sorry.

Any help with these leak(s) would be very much welcomed and appreciated!

Places to look/analyse include:
* The `sh.pathlist` linked list, and the `Pathcomp_t` (pathname component) struct.
* The `path_addpath` and `path_delete` functions from path.c, and where/how they're used.
* `put_restricted` in init.c, which is called (via the `RESTRICTED_disc` discipline) whenever an assignment to `PATH`, `FPATH`, `SHELL` or `ENV` is made.
